#!/bin/bash
#SBATCH --partition=debugq
#SBATCH --nodes=1
#SBATCH --tasks=10
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH -J charges
#SBATCH --output=./out/slurm-%j.out
###SBATCH --mail-user=dpirvu@perimeterinstitute.ca

python3 ./bubble_codes/conserved_charges.py >> ./out/output_conserved.txt

#python3 ./out/conserved_charges0.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges1.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges2.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges3.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges4.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges5.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges6.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges7.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges8.py >> ./out/output_conserved.txt &
#python3 ./out/conserved_charges9.py >> ./out/output_conserved.txt &
#wait

print('Done')